# Generated by Django 4.0.1 on 2022-01-16 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('photo', models.ImageField(upload_to='product/', verbose_name='产品图片')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('product_type', models.CharField(max_length=100, verbose_name='产品类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('sort', models.CharField(max_length=100, verbose_name='排序')),
                ('state', models.CharField(default='1', max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('-publish_date',),
            },
        ),
    ]
