# Generated by Django 4.0.1 on 2022-01-15 18:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
                ('news_type', models.CharField(choices=[('企业要闻', '企业要闻'), ('行业新闻', '行业新闻'), ('通知公告', '通知公告')], max_length=50, verbose_name='新闻类型')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='图片')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('sort', models.CharField(max_length=100, verbose_name='排序')),
                ('state', models.CharField(default='1', max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻列表',
                'ordering': ['-publish_date'],
            },
        ),
    ]
