# Generated by Django 4.0.1 on 2022-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('photo', models.ImageField(blank=True, upload_to='award/', verbose_name='图片')),
                ('sort', models.CharField(max_length=100, verbose_name='排序')),
                ('state', models.CharField(default='1', max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': '荣誉资质',
                'verbose_name_plural': '荣誉资质',
                'db_table': 'award',
                'ordering': ('-id',),
            },
        ),
    ]
