# Generated by Django 4.0.1 on 2022-01-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f02_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='award',
            table=None,
        ),
    ]
