# Generated by Django 4.0.1 on 2022-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f02_profile', '0002_alter_award_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title',
            field=models.TextField(default=1, max_length=500, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(default=2, max_length=500, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='sort',
            field=models.CharField(blank=True, max_length=100, verbose_name='排序'),
        ),
    ]
