# Generated by Django 4.0.1 on 2022-01-16 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='招聘岗位')),
                ('description', models.TextField(verbose_name='招聘要求')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('person_id', models.CharField(max_length=30, verbose_name='身份证号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('birth', models.DateField(default='2022-01-16', verbose_name='出生日期')),
                ('edu', models.CharField(default='本科', max_length=50, verbose_name='学历')),
                ('school', models.CharField(max_length=50, verbose_name='毕业学校')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('position', models.CharField(max_length=40, verbose_name='申请职位')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='项目经验')),
                ('photo', models.ImageField(upload_to='contact/recruit/%Y-%m-%d', verbose_name='个人照片')),
                ('status', models.IntegerField(choices=[(1, '未审'), (2, '通过'), (3, '未通过')], default=1, verbose_name='面试成绩')),
                ('publish_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '简历信息',
                'verbose_name_plural': '简历信息',
                'ordering': ('-status', '-publish_data'),
            },
        ),
    ]
